labels = {
    "autonomy_pressure": "I feel pressured in my life",
    "autonomy_express": "I generally feel free to express my ideas and opinions",
    "autonomy_decide": "I feel like I am free to decide for myself how to live my life",
    "autonomy_told": "In my daily life I often have to do what I am told",
    "autonomy_myself": "I feel I can pretty much be myself in daily situations",
    "autonomy_choice": "I have enough choice about how I spend my time",
    "life_satisfaction": "Overall, how satisfied are you with your life nowadays?",
    "optimism_future": "I am optimistic about my future",
    "optimism_best": "In uncertain times, I expect the best",
    "optimism_good": "I think good things are going to happen to me",
    "optimism_work": "I believe that things will work out, no matter how difficult they seem",
    "wellbeing_optimistic": "I've been feeling optimistic about the future",
    "wellbeing_useful": "I've been feeling useful",
    "wellbeing_relaxed": "I've been feeling relaxed",
    "wellbeing_problems": "I've been dealing with problems well",
    "wellbeing_thinking": "I've been thinking clearly",
    "wellbeing_close": "I've been feeling close to other people",
    "wellbeing_mind": "I've been able to make up my own mind about things",
    "esteem_satisfied": "On the whole, I am satisfied with myself",
    "esteem_qualities": "I feel that I have a number of good qualities",
    "esteem_well": "I am able to do things as well as most other people",
    "esteem_value": "I am a person of value",
    "esteem_good": "I feel good about myself",
    "stress_control": "During the last month, how often have you... felt you were unable to control the important things in your life?",
    "stress_overcome": "During the last month, how often have you... felt that difficulties were piling up so high that you could not overcome them?",
    "stress_confident": "During the last month, how often have you... felt confident about your ability to handle your personal problems?",
    "stress_way": "During the last month, how often have you... felt that things were going your way?",
    "appearance_happy": "How happy are you with your appearance (the way that you look)?",
    "appearance_feel": "My appearance affects how I feel about myself",
    "negative_lonely": "I feel lonely",
    "negative_unhappy": "I am unhappy",
    "negative_like": "Nobody likes me",
    "negative_cry": "I cry a lot",
    "negative_school": "I worry when I am at school",
    "negative_worry": "I worry a lot",
    "negative_sleep": "I have problems sleeping",
    "negative_wake": "I wake up in the night",
    "negative_shy": "I am shy",
    "negative_scared": "I feel scared",
    "lonely": "How often do you feel lonely?",
    "support_ways": "I have ways to support myself (e.g. to cope, or help myself feel better)",
    "support_look": "I know where to look for advice on how to support myself",
    "sleep": "Is the amount of sleep you normally get enough for you to feel awake and concentrate on your school work during the day?",
    "physical_days": "How many days in a usual week are you physically active?",
    "physical_hours": "How long on average do you spend being physically active?",
    "free_like": "How often can you do things that you like in your free time?",
    "media_hours": "On a normal weekday during term time, how much time do you spend on social media?",
    "places_freq": "How many activities/places are there in your local area that you choose to or would want to go to in your free time?",
    "places_barriers___1": "There's nothing to do",
    "places_barriers___2": "I'm unable to get there and back",
    "places_barriers___3": "It's too expensive (to get there or take part)",
    "places_barriers___4": "Poor weather",
    "places_barriers___5": "I have no-one to go with",
    "places_barriers___6": "It's too busy",
    "places_barriers___7": "I feel uncomfortable/anxious about other people who might be there",
    "places_barriers___8": "My parents/carers don't allow me to go",
    "places_barriers___9": "Other",
    "school_belong": "I feel that I belong at my school",
    "staff_interest": "At school there is an adult who... is interested in my schoolwork",
    "staff_believe": "At school there is an adult who... believes that I will be a success",
    "staff_best": "At school there is an adult who... wants me to do my best",
    "staff_listen": "At school there is an adult who... listens to me when I have something to say",
    "staff_talk_occur": "Have you ever talked about feeling down with... an adult at school?",  # Changed to match synthetic data
    "staff_talk_listen": "Did you feel listened to when you spoke with... an adult at school?",
    "staff_talk_helpful": "Did you receive advice that you found helpful from... an adult at school?",
    "staff_talk_if": "How would you feel about speaking with... an adult at school?",
    "accept_staff": "Do you feel accepted as you are by... adults at your school?",
    "home_interest": "At home there is an adult who... is interested in my schoolwork",
    "home_believe": "At home there is an adult who... believes that I will be a success",
    "home_best": "At home there is an adult who... wants me to do my best",
    "home_listen": "At home there is an adult who... listens to me when I have something to say",
    "home_talk": "Have you ever talked about feeling down with... one of your parents/carers?",
    "home_talk_listen": "Did you feel listened to when you spoke with... one of your parents/carers?",
    "home_talk_helpful": "Did you receive advice that you found helpful from... one of your parents/carers?",
    "home_talk_if": "How would you feel about speaking with... one of your parents/carers?",
    "accept_home": "Do you feel accepted as you are... by your parents/carers?",
    "home_happy": "How happy are you with the home that you live in?",
    "local_safe": "How safe do you feel when in your local area?",
    "local_support": "People around here support each other with their wellbeing",
    "local_trust": "You can trust people around here",
    "local_neighbours": "I could ask for help or a favour from neighbours",
    "local_places": "There are good places to spend your free time (e.g., leisure centres, parks, shops)",
    "discrim_race": "How often do people make you feel bad because of... your race, skin colour or where you were born?",
    "discrim_gender": "How often do people make you feel bad because of... your gender?",
    "discrim_orientation": "How often do people make you feel bad because of... your sexual orientation?",
    "discrim_disability": "How often do people make you feel bad because of... disability?",
    "discrim_faith": "How often do people make you feel bad because of... your religion/faith?",
    "belong_local": "I feel like I belong in my local area",
    "accept_local": "Do you feel accepted as you are... by people in your local area?",
    "wealth": "Compared to your friends, is your family richer, poorer or about the same?",
    "future_options": "How many options are available?",
    "future_interest": "How do you feel about the options available?",
    "future_support": "Do you feel (or think you would feel) supported to explore options that interest you, even if no-one else around you has done them before?",
    "climate": "How often do you worry about the impact of climate change on your future?",
    "social_along": "I get along with people around me",
    "social_time": "People like to spend time with me",
    "social_support": "I feel supported by my friends",
    "social_hard": "My friends care about me when times are hard (for example if I am sick or have done something wrong)",
    "bully_physical": "How often do you get physically bullied at school (getting hit, pushed around, threatened, or having belongings stolen)?",
    "bully_other": "How often do you get bullied in other ways at school (insults, slurs, name calling, threats, getting left out or excluded by others, or having rumours spread about you on purpose)?",
    "bully_cyber": "How often do you get cyber-bullied (someone sending mean text or online messages about you, creating a website making fun of you, posting pictures that make you look bad online, or sharing them with others)?",
    "peer_talk": "Have you ever talked about feeling down with... another person your age?",
    "peer_talk_listen": "Did you feel listened to when you spoke with... another person your age?",
    "peer_talk_helpful": "Did you receive advice that you found helpful from... another person your age?",
    "peer_talk_if": "How would you feel about speaking with... another person your age?",
    "accept_peer": "Do you feel accepted as you are... by other people your age?",
}
