topic_name_dict = {
    "autonomy": "Autonomy",
    "life_satisfaction": "Life satisfaction",
    "optimism": "Optimism",
    "wellbeing": "Psychological wellbeing",
    "esteem": "Self-esteem",
    "stress": "Stress and coping",
    "appearance": "Feelings around appearance",
    "negative": "Negative affect",
    "lonely": "Loneliness",
    "support": "Supporting own wellbeing",
    "sleep": "Sleep",
    "physical": "Physical activity",
    "free_like": "Free time",
    "media": "Social media use",
    "places": "Places to go and things to do",
    "staff_talk": "Talking about feelings at school",
    "peer_talk": "Talking about feelings with peers",
    "home_talk": "Talking about feelings at home",
    "accept": "Acceptance",
    "school_belong": "School connection",
    "staff_relationship": "Support from staff",
    "home_relationship": "Support from parents/carers",
    "home_happy": "Home environment",
    "local_env": "Local environment",
    "discrim": "Discrimination",
    "belong_local": "Local connection",
    "wealth": "Relative wealth",
    "future": "Future opportunities",
    "climate": "Climate change",
    "social": "Support from friends",
    "bully": "Bullying",
}
